//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HRPerformanceGoals.intra.chsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CHSServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CHSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPersonProfileByLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPersonProfileByTkidOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllEmployeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllAttorneysOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllPartnersOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMTPEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMTPEmailOutgoingOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCountriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCountryStatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllEliteClientTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEliteClientListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEliteClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentPartnerByDeptCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPractriceAreaByDeptCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrackAppUsageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CHSService() {
            this.Url = global::HRPerformanceGoals.Properties.Settings.Default.HRPerformanceGoals_intra_chsService_CHSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPersonProfileByLoginCompletedEventHandler GetPersonProfileByLoginCompleted;
        
        /// <remarks/>
        public event GetPersonProfileByTkidCompletedEventHandler GetPersonProfileByTkidCompleted;
        
        /// <remarks/>
        public event GetAllEmployeesCompletedEventHandler GetAllEmployeesCompleted;
        
        /// <remarks/>
        public event GetAllAttorneysCompletedEventHandler GetAllAttorneysCompleted;
        
        /// <remarks/>
        public event GetAllPartnersCompletedEventHandler GetAllPartnersCompleted;
        
        /// <remarks/>
        public event SendSMTPEmailCompletedEventHandler SendSMTPEmailCompleted;
        
        /// <remarks/>
        public event SendSMTPEmailOutgoingCompletedEventHandler SendSMTPEmailOutgoingCompleted;
        
        /// <remarks/>
        public event GetAllCountriesCompletedEventHandler GetAllCountriesCompleted;
        
        /// <remarks/>
        public event GetAllCountryStatesCompletedEventHandler GetAllCountryStatesCompleted;
        
        /// <remarks/>
        public event GetAllEliteClientTypeCompletedEventHandler GetAllEliteClientTypeCompleted;
        
        /// <remarks/>
        public event GetEliteClientListCompletedEventHandler GetEliteClientListCompleted;
        
        /// <remarks/>
        public event GetEliteClientCompletedEventHandler GetEliteClientCompleted;
        
        /// <remarks/>
        public event GetDepartmentsCompletedEventHandler GetDepartmentsCompleted;
        
        /// <remarks/>
        public event GetDepartmentPartnerByDeptCodeCompletedEventHandler GetDepartmentPartnerByDeptCodeCompleted;
        
        /// <remarks/>
        public event GetPractriceAreaByDeptCodeCompletedEventHandler GetPractriceAreaByDeptCodeCompleted;
        
        /// <remarks/>
        public event TrackAppUsageCompletedEventHandler TrackAppUsageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPersonProfileByLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonVO GetPersonProfileByLogin(string Login) {
            object[] results = this.Invoke("GetPersonProfileByLogin", new object[] {
                        Login});
            return ((PersonVO)(results[0]));
        }
        
        /// <remarks/>
        public void GetPersonProfileByLoginAsync(string Login) {
            this.GetPersonProfileByLoginAsync(Login, null);
        }
        
        /// <remarks/>
        public void GetPersonProfileByLoginAsync(string Login, object userState) {
            if ((this.GetPersonProfileByLoginOperationCompleted == null)) {
                this.GetPersonProfileByLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersonProfileByLoginOperationCompleted);
            }
            this.InvokeAsync("GetPersonProfileByLogin", new object[] {
                        Login}, this.GetPersonProfileByLoginOperationCompleted, userState);
        }
        
        private void OnGetPersonProfileByLoginOperationCompleted(object arg) {
            if ((this.GetPersonProfileByLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersonProfileByLoginCompleted(this, new GetPersonProfileByLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPersonProfileByTkid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonVO GetPersonProfileByTkid(string Tkid) {
            object[] results = this.Invoke("GetPersonProfileByTkid", new object[] {
                        Tkid});
            return ((PersonVO)(results[0]));
        }
        
        /// <remarks/>
        public void GetPersonProfileByTkidAsync(string Tkid) {
            this.GetPersonProfileByTkidAsync(Tkid, null);
        }
        
        /// <remarks/>
        public void GetPersonProfileByTkidAsync(string Tkid, object userState) {
            if ((this.GetPersonProfileByTkidOperationCompleted == null)) {
                this.GetPersonProfileByTkidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPersonProfileByTkidOperationCompleted);
            }
            this.InvokeAsync("GetPersonProfileByTkid", new object[] {
                        Tkid}, this.GetPersonProfileByTkidOperationCompleted, userState);
        }
        
        private void OnGetPersonProfileByTkidOperationCompleted(object arg) {
            if ((this.GetPersonProfileByTkidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPersonProfileByTkidCompleted(this, new GetPersonProfileByTkidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllEmployees", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonVO[] GetAllEmployees() {
            object[] results = this.Invoke("GetAllEmployees", new object[0]);
            return ((PersonVO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllEmployeesAsync() {
            this.GetAllEmployeesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllEmployeesAsync(object userState) {
            if ((this.GetAllEmployeesOperationCompleted == null)) {
                this.GetAllEmployeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllEmployeesOperationCompleted);
            }
            this.InvokeAsync("GetAllEmployees", new object[0], this.GetAllEmployeesOperationCompleted, userState);
        }
        
        private void OnGetAllEmployeesOperationCompleted(object arg) {
            if ((this.GetAllEmployeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllEmployeesCompleted(this, new GetAllEmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllAttorneys", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonVO[] GetAllAttorneys() {
            object[] results = this.Invoke("GetAllAttorneys", new object[0]);
            return ((PersonVO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllAttorneysAsync() {
            this.GetAllAttorneysAsync(null);
        }
        
        /// <remarks/>
        public void GetAllAttorneysAsync(object userState) {
            if ((this.GetAllAttorneysOperationCompleted == null)) {
                this.GetAllAttorneysOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllAttorneysOperationCompleted);
            }
            this.InvokeAsync("GetAllAttorneys", new object[0], this.GetAllAttorneysOperationCompleted, userState);
        }
        
        private void OnGetAllAttorneysOperationCompleted(object arg) {
            if ((this.GetAllAttorneysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllAttorneysCompleted(this, new GetAllAttorneysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllPartners", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonVO[] GetAllPartners() {
            object[] results = this.Invoke("GetAllPartners", new object[0]);
            return ((PersonVO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPartnersAsync() {
            this.GetAllPartnersAsync(null);
        }
        
        /// <remarks/>
        public void GetAllPartnersAsync(object userState) {
            if ((this.GetAllPartnersOperationCompleted == null)) {
                this.GetAllPartnersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPartnersOperationCompleted);
            }
            this.InvokeAsync("GetAllPartners", new object[0], this.GetAllPartnersOperationCompleted, userState);
        }
        
        private void OnGetAllPartnersOperationCompleted(object arg) {
            if ((this.GetAllPartnersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPartnersCompleted(this, new GetAllPartnersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMTPEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendSMTPEmail(EmailVO message) {
            this.Invoke("SendSMTPEmail", new object[] {
                        message});
        }
        
        /// <remarks/>
        public void SendSMTPEmailAsync(EmailVO message) {
            this.SendSMTPEmailAsync(message, null);
        }
        
        /// <remarks/>
        public void SendSMTPEmailAsync(EmailVO message, object userState) {
            if ((this.SendSMTPEmailOperationCompleted == null)) {
                this.SendSMTPEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMTPEmailOperationCompleted);
            }
            this.InvokeAsync("SendSMTPEmail", new object[] {
                        message}, this.SendSMTPEmailOperationCompleted, userState);
        }
        
        private void OnSendSMTPEmailOperationCompleted(object arg) {
            if ((this.SendSMTPEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMTPEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMTPEmailOutgoing", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendSMTPEmailOutgoing(EmailVO message) {
            this.Invoke("SendSMTPEmailOutgoing", new object[] {
                        message});
        }
        
        /// <remarks/>
        public void SendSMTPEmailOutgoingAsync(EmailVO message) {
            this.SendSMTPEmailOutgoingAsync(message, null);
        }
        
        /// <remarks/>
        public void SendSMTPEmailOutgoingAsync(EmailVO message, object userState) {
            if ((this.SendSMTPEmailOutgoingOperationCompleted == null)) {
                this.SendSMTPEmailOutgoingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMTPEmailOutgoingOperationCompleted);
            }
            this.InvokeAsync("SendSMTPEmailOutgoing", new object[] {
                        message}, this.SendSMTPEmailOutgoingOperationCompleted, userState);
        }
        
        private void OnSendSMTPEmailOutgoingOperationCompleted(object arg) {
            if ((this.SendSMTPEmailOutgoingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMTPEmailOutgoingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCountries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CountryVO[] GetAllCountries() {
            object[] results = this.Invoke("GetAllCountries", new object[0]);
            return ((CountryVO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCountriesAsync() {
            this.GetAllCountriesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCountriesAsync(object userState) {
            if ((this.GetAllCountriesOperationCompleted == null)) {
                this.GetAllCountriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCountriesOperationCompleted);
            }
            this.InvokeAsync("GetAllCountries", new object[0], this.GetAllCountriesOperationCompleted, userState);
        }
        
        private void OnGetAllCountriesOperationCompleted(object arg) {
            if ((this.GetAllCountriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCountriesCompleted(this, new GetAllCountriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCountryStates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StateVO[] GetAllCountryStates(string CountryAbbr) {
            object[] results = this.Invoke("GetAllCountryStates", new object[] {
                        CountryAbbr});
            return ((StateVO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCountryStatesAsync(string CountryAbbr) {
            this.GetAllCountryStatesAsync(CountryAbbr, null);
        }
        
        /// <remarks/>
        public void GetAllCountryStatesAsync(string CountryAbbr, object userState) {
            if ((this.GetAllCountryStatesOperationCompleted == null)) {
                this.GetAllCountryStatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCountryStatesOperationCompleted);
            }
            this.InvokeAsync("GetAllCountryStates", new object[] {
                        CountryAbbr}, this.GetAllCountryStatesOperationCompleted, userState);
        }
        
        private void OnGetAllCountryStatesOperationCompleted(object arg) {
            if ((this.GetAllCountryStatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCountryStatesCompleted(this, new GetAllCountryStatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllEliteClientType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EliteClientTypeVO[] GetAllEliteClientType() {
            object[] results = this.Invoke("GetAllEliteClientType", new object[0]);
            return ((EliteClientTypeVO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllEliteClientTypeAsync() {
            this.GetAllEliteClientTypeAsync(null);
        }
        
        /// <remarks/>
        public void GetAllEliteClientTypeAsync(object userState) {
            if ((this.GetAllEliteClientTypeOperationCompleted == null)) {
                this.GetAllEliteClientTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllEliteClientTypeOperationCompleted);
            }
            this.InvokeAsync("GetAllEliteClientType", new object[0], this.GetAllEliteClientTypeOperationCompleted, userState);
        }
        
        private void OnGetAllEliteClientTypeOperationCompleted(object arg) {
            if ((this.GetAllEliteClientTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllEliteClientTypeCompleted(this, new GetAllEliteClientTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEliteClientList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EliteClientVO[] GetEliteClientList() {
            object[] results = this.Invoke("GetEliteClientList", new object[0]);
            return ((EliteClientVO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEliteClientListAsync() {
            this.GetEliteClientListAsync(null);
        }
        
        /// <remarks/>
        public void GetEliteClientListAsync(object userState) {
            if ((this.GetEliteClientListOperationCompleted == null)) {
                this.GetEliteClientListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEliteClientListOperationCompleted);
            }
            this.InvokeAsync("GetEliteClientList", new object[0], this.GetEliteClientListOperationCompleted, userState);
        }
        
        private void OnGetEliteClientListOperationCompleted(object arg) {
            if ((this.GetEliteClientListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEliteClientListCompleted(this, new GetEliteClientListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEliteClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EliteClientVO GetEliteClient(string ClientNumber) {
            object[] results = this.Invoke("GetEliteClient", new object[] {
                        ClientNumber});
            return ((EliteClientVO)(results[0]));
        }
        
        /// <remarks/>
        public void GetEliteClientAsync(string ClientNumber) {
            this.GetEliteClientAsync(ClientNumber, null);
        }
        
        /// <remarks/>
        public void GetEliteClientAsync(string ClientNumber, object userState) {
            if ((this.GetEliteClientOperationCompleted == null)) {
                this.GetEliteClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEliteClientOperationCompleted);
            }
            this.InvokeAsync("GetEliteClient", new object[] {
                        ClientNumber}, this.GetEliteClientOperationCompleted, userState);
        }
        
        private void OnGetEliteClientOperationCompleted(object arg) {
            if ((this.GetEliteClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEliteClientCompleted(this, new GetEliteClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepartmentVO[] GetDepartments() {
            object[] results = this.Invoke("GetDepartments", new object[0]);
            return ((DepartmentVO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentsAsync() {
            this.GetDepartmentsAsync(null);
        }
        
        /// <remarks/>
        public void GetDepartmentsAsync(object userState) {
            if ((this.GetDepartmentsOperationCompleted == null)) {
                this.GetDepartmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentsOperationCompleted);
            }
            this.InvokeAsync("GetDepartments", new object[0], this.GetDepartmentsOperationCompleted, userState);
        }
        
        private void OnGetDepartmentsOperationCompleted(object arg) {
            if ((this.GetDepartmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentsCompleted(this, new GetDepartmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartmentPartnerByDeptCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonVO[] GetDepartmentPartnerByDeptCode(string DeptCode) {
            object[] results = this.Invoke("GetDepartmentPartnerByDeptCode", new object[] {
                        DeptCode});
            return ((PersonVO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentPartnerByDeptCodeAsync(string DeptCode) {
            this.GetDepartmentPartnerByDeptCodeAsync(DeptCode, null);
        }
        
        /// <remarks/>
        public void GetDepartmentPartnerByDeptCodeAsync(string DeptCode, object userState) {
            if ((this.GetDepartmentPartnerByDeptCodeOperationCompleted == null)) {
                this.GetDepartmentPartnerByDeptCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentPartnerByDeptCodeOperationCompleted);
            }
            this.InvokeAsync("GetDepartmentPartnerByDeptCode", new object[] {
                        DeptCode}, this.GetDepartmentPartnerByDeptCodeOperationCompleted, userState);
        }
        
        private void OnGetDepartmentPartnerByDeptCodeOperationCompleted(object arg) {
            if ((this.GetDepartmentPartnerByDeptCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentPartnerByDeptCodeCompleted(this, new GetDepartmentPartnerByDeptCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPractriceAreaByDeptCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PracticeAreaVO[] GetPractriceAreaByDeptCode(string DeptCode) {
            object[] results = this.Invoke("GetPractriceAreaByDeptCode", new object[] {
                        DeptCode});
            return ((PracticeAreaVO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPractriceAreaByDeptCodeAsync(string DeptCode) {
            this.GetPractriceAreaByDeptCodeAsync(DeptCode, null);
        }
        
        /// <remarks/>
        public void GetPractriceAreaByDeptCodeAsync(string DeptCode, object userState) {
            if ((this.GetPractriceAreaByDeptCodeOperationCompleted == null)) {
                this.GetPractriceAreaByDeptCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPractriceAreaByDeptCodeOperationCompleted);
            }
            this.InvokeAsync("GetPractriceAreaByDeptCode", new object[] {
                        DeptCode}, this.GetPractriceAreaByDeptCodeOperationCompleted, userState);
        }
        
        private void OnGetPractriceAreaByDeptCodeOperationCompleted(object arg) {
            if ((this.GetPractriceAreaByDeptCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPractriceAreaByDeptCodeCompleted(this, new GetPractriceAreaByDeptCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrackAppUsage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TrackAppUsage(string login, string place) {
            this.Invoke("TrackAppUsage", new object[] {
                        login,
                        place});
        }
        
        /// <remarks/>
        public void TrackAppUsageAsync(string login, string place) {
            this.TrackAppUsageAsync(login, place, null);
        }
        
        /// <remarks/>
        public void TrackAppUsageAsync(string login, string place, object userState) {
            if ((this.TrackAppUsageOperationCompleted == null)) {
                this.TrackAppUsageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrackAppUsageOperationCompleted);
            }
            this.InvokeAsync("TrackAppUsage", new object[] {
                        login,
                        place}, this.TrackAppUsageOperationCompleted, userState);
        }
        
        private void OnTrackAppUsageOperationCompleted(object arg) {
            if ((this.TrackAppUsageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrackAppUsageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonVO {
        
        private string loginField;
        
        private string tKIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string fullNameField;
        
        private string firstLastNameField;
        
        private string friendlyNameField;
        
        private string emailField;
        
        private string extensionField;
        
        private string jobTitleField;
        
        private string officeFloorField;
        
        private string departmentField;
        
        private string departmentCodeField;
        
        private string joinedDateField;
        
        private bool isContractorField;
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string TKID {
            get {
                return this.tKIDField;
            }
            set {
                this.tKIDField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstLastName {
            get {
                return this.firstLastNameField;
            }
            set {
                this.firstLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FriendlyName {
            get {
                return this.friendlyNameField;
            }
            set {
                this.friendlyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        public string JobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        public string OfficeFloor {
            get {
                return this.officeFloorField;
            }
            set {
                this.officeFloorField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentCode {
            get {
                return this.departmentCodeField;
            }
            set {
                this.departmentCodeField = value;
            }
        }
        
        /// <remarks/>
        public string JoinedDate {
            get {
                return this.joinedDateField;
            }
            set {
                this.joinedDateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsContractor {
            get {
                return this.isContractorField;
            }
            set {
                this.isContractorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PracticeAreaVO {
        
        private string areaCodeField;
        
        private string areaNameField;
        
        private string deptCodeField;
        
        /// <remarks/>
        public string AreaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AreaName {
            get {
                return this.areaNameField;
            }
            set {
                this.areaNameField = value;
            }
        }
        
        /// <remarks/>
        public string DeptCode {
            get {
                return this.deptCodeField;
            }
            set {
                this.deptCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DepartmentVO {
        
        private string deptCodeField;
        
        private string deptNameField;
        
        /// <remarks/>
        public string DeptCode {
            get {
                return this.deptCodeField;
            }
            set {
                this.deptCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DeptName {
            get {
                return this.deptNameField;
            }
            set {
                this.deptNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EliteClientVO {
        
        private string clientNameField;
        
        private string clientNameContiField;
        
        private string clientNumberField;
        
        private string address56Field;
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string address4Field;
        
        private string cityField;
        
        private string countryField;
        
        private string stateField;
        
        private string zipCodeField;
        
        private string clientPhoneField;
        
        private string contactField;
        
        private string clientTypeField;
        
        private string statusField;
        
        private string clientManagementAttyField;
        
        private string clientOriginatingAttyField;
        
        private string clientStoryField;
        
        private string matterDescriptionField;
        
        private string businessDescriptionField;
        
        private string isClientConfidentialField;
        
        /// <remarks/>
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        public string ClientNameConti {
            get {
                return this.clientNameContiField;
            }
            set {
                this.clientNameContiField = value;
            }
        }
        
        /// <remarks/>
        public string ClientNumber {
            get {
                return this.clientNumberField;
            }
            set {
                this.clientNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Address56 {
            get {
                return this.address56Field;
            }
            set {
                this.address56Field = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string Address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
            }
        }
        
        /// <remarks/>
        public string Address4 {
            get {
                return this.address4Field;
            }
            set {
                this.address4Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClientPhone {
            get {
                return this.clientPhoneField;
            }
            set {
                this.clientPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string ClientType {
            get {
                return this.clientTypeField;
            }
            set {
                this.clientTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ClientManagementAtty {
            get {
                return this.clientManagementAttyField;
            }
            set {
                this.clientManagementAttyField = value;
            }
        }
        
        /// <remarks/>
        public string ClientOriginatingAtty {
            get {
                return this.clientOriginatingAttyField;
            }
            set {
                this.clientOriginatingAttyField = value;
            }
        }
        
        /// <remarks/>
        public string ClientStory {
            get {
                return this.clientStoryField;
            }
            set {
                this.clientStoryField = value;
            }
        }
        
        /// <remarks/>
        public string MatterDescription {
            get {
                return this.matterDescriptionField;
            }
            set {
                this.matterDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessDescription {
            get {
                return this.businessDescriptionField;
            }
            set {
                this.businessDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string IsClientConfidential {
            get {
                return this.isClientConfidentialField;
            }
            set {
                this.isClientConfidentialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EliteClientTypeVO {
        
        private string bizTypeField;
        
        private string bizDescriptionField;
        
        /// <remarks/>
        public string BizType {
            get {
                return this.bizTypeField;
            }
            set {
                this.bizTypeField = value;
            }
        }
        
        /// <remarks/>
        public string BizDescription {
            get {
                return this.bizDescriptionField;
            }
            set {
                this.bizDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StateVO {
        
        private string abbrNameField;
        
        private string fullNameField;
        
        private string countryField;
        
        private string countryAbbrField;
        
        /// <remarks/>
        public string AbbrName {
            get {
                return this.abbrNameField;
            }
            set {
                this.abbrNameField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string CountryAbbr {
            get {
                return this.countryAbbrField;
            }
            set {
                this.countryAbbrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CountryVO {
        
        private string countryAbbrField;
        
        private string countryField;
        
        private string countryCodeField;
        
        /// <remarks/>
        public string CountryAbbr {
            get {
                return this.countryAbbrField;
            }
            set {
                this.countryAbbrField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileVO {
        
        private byte[] uplFileField;
        
        private string uplFileNameField;
        
        private string uplFileExtField;
        
        private string uplFilePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] uplFile {
            get {
                return this.uplFileField;
            }
            set {
                this.uplFileField = value;
            }
        }
        
        /// <remarks/>
        public string uplFileName {
            get {
                return this.uplFileNameField;
            }
            set {
                this.uplFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string uplFileExt {
            get {
                return this.uplFileExtField;
            }
            set {
                this.uplFileExtField = value;
            }
        }
        
        /// <remarks/>
        public string uplFilePath {
            get {
                return this.uplFilePathField;
            }
            set {
                this.uplFilePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmailVO {
        
        private string fromField;
        
        private string[] toField;
        
        private string[] ccField;
        
        private string[] bccField;
        
        private string subjectField;
        
        private string bodyField;
        
        private FileVO[] attachmentField;
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string[] To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string[] Cc {
            get {
                return this.ccField;
            }
            set {
                this.ccField = value;
            }
        }
        
        /// <remarks/>
        public string[] Bcc {
            get {
                return this.bccField;
            }
            set {
                this.bccField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public FileVO[] Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetPersonProfileByLoginCompletedEventHandler(object sender, GetPersonProfileByLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersonProfileByLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersonProfileByLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetPersonProfileByTkidCompletedEventHandler(object sender, GetPersonProfileByTkidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPersonProfileByTkidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPersonProfileByTkidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetAllEmployeesCompletedEventHandler(object sender, GetAllEmployeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetAllAttorneysCompletedEventHandler(object sender, GetAllAttorneysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllAttorneysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllAttorneysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetAllPartnersCompletedEventHandler(object sender, GetAllPartnersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPartnersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPartnersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void SendSMTPEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void SendSMTPEmailOutgoingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetAllCountriesCompletedEventHandler(object sender, GetAllCountriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCountriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCountriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CountryVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CountryVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetAllCountryStatesCompletedEventHandler(object sender, GetAllCountryStatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCountryStatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCountryStatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StateVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StateVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetAllEliteClientTypeCompletedEventHandler(object sender, GetAllEliteClientTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllEliteClientTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllEliteClientTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EliteClientTypeVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EliteClientTypeVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetEliteClientListCompletedEventHandler(object sender, GetEliteClientListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEliteClientListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEliteClientListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EliteClientVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EliteClientVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetEliteClientCompletedEventHandler(object sender, GetEliteClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEliteClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEliteClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EliteClientVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EliteClientVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetDepartmentsCompletedEventHandler(object sender, GetDepartmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepartmentVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepartmentVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetDepartmentPartnerByDeptCodeCompletedEventHandler(object sender, GetDepartmentPartnerByDeptCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentPartnerByDeptCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentPartnerByDeptCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetPractriceAreaByDeptCodeCompletedEventHandler(object sender, GetPractriceAreaByDeptCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPractriceAreaByDeptCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPractriceAreaByDeptCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PracticeAreaVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PracticeAreaVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void TrackAppUsageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591